---
abstract: 'The great new MooseX::FSM!'
author:
  - 'Gordon Irving <goraxe@goraxe.me.uk>'
build_requires:
  Moose: 0.72
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
name: MooseX-FSM
provides:
  Moose::Meta::Attribute::Custom::Trait::State:
    file: lib/MooseX/FSM/State.pm
  MooseX::FSM:
    file: lib/MooseX/FSM.pm
    version: 0.01
  MooseX::FSM::Role::Object:
    file: lib/MooseX/FSM.pm
  MooseX::FSM::State:
    file: lib/MooseX/FSM/State.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
